version: '3.4'

services:
  dockerexample:
    image: ${DOCKER_REGISTRY-}dockerexample
    build:
      context: .
      dockerfile: DockerExample/Dockerfile
  environment:
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_HTTPS_PORT=443
        ports:
          - "80:80
          - "443:443"
